CREATE TABLE ESPECTACULO
(
	ID NUMBER NOT NULL,
	ID_COMPANIA NUMBER NOT NULL,
	NOMBRE VARCHAR(255),
	DURACION NUMBER NOT NULL,
	LENGUAJE VARCHAR(255),
	COSTO_PRODUCCION NUMBER NOT NULL,
	PUBLICO VARCHAR(255),
	DESCRIPCION VARCHAR(255),
	TRADUCCION NUMBER NOT NULL,
		
	CONSTRAINT ESPECTACULO_PK PRIMARY KEY(ID),
	CONSTRAINT FK_COMPANIA FOREIGN KEY (ID_COMPANIA) REFERENCE COMPANIA (ID)
);

INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (1,'72','Charlotte Rosario','86','Czech Republic','032','todos ','a, aliquet vel, vulputate',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (2,'77','Hayley Larson','73','Armenia','226','todos ','facilisis eget, ipsum. Donec',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (3,'82','Kathleen Keller','99','Montenegro','049',' adulto','Sed',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (4,'98','Honorato Warner','77','Anguilla','106',' joven ','Quisque ac libero',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (5,'88','Maggy Koch','68','Bahrain','211','todos ','egestas rhoncus. Proin',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (6,'25','Garrett Rojas','69','Korea, South','328','todos ','et,',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (7,'30','Keith Martinez','72','Bermuda','799',' joven ','non, egestas a, dui.',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (8,'36','Desirae Armstrong','41','Cyprus','862',' adulto','pede. Suspendisse dui. Fusce',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (9,'63','Kim Frank','36','Faroe Islands','353','todos ','lectus. Cum',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (10,'99','Yetta Pate','43','Congo, the Democratic Republic of the','141',' adulto','sit amet',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (11,'59','Merritt Michael','88','Belarus','729',' adulto','ultrices. Vivamus rhoncus.',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (12,'35','Karen Perez','83','Congo (Brazzaville)','719',' adulto','adipiscing',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (13,'49','Quamar Brock','74','Curaçao','063','todos ','amet ornare',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (14,'29','Kato Moses','60','Turkey','082',' adulto','placerat, orci lacus vestibulum lorem,',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (15,'70','Hiroko Love','78','Mongolia','301','todos ','viverra. Maecenas iaculis aliquet diam.',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (16,'78','Hu Faulkner','38','Morocco','326','todos ','auctor odio a purus.',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (17,'31','Christian Macias','07','Belarus','810',' adulto','at, egestas a, scelerisque sed,',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (18,'64','Anne Booker','76','Kyrgyzstan','223','todos ','tortor nibh sit amet orci.',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (19,'55','Ariel Campos','29','Central African Republic','409','todos ','non justo. Proin non massa',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (20,'85','Thane Chandler','41','Bolivia','302',' joven ','feugiat metus sit amet',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (21,'69','Christopher Baldwin','86','Spain','907','todos ','leo elementum sem, vitae aliquam',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (22,'79','Serina Vega','95','Algeria','633',' joven ','aptent taciti sociosqu',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (23,'49','Graham Atkins','81','Yemen','026',' joven ','tristique',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (24,'63','Jeremy Ruiz','64','Peru','651','todos ','vel nisl.',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (25,'37','Savannah Ramos','80','Guatemala','347',' joven ','at, libero.',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (26,'18','Tad Bernard','53','Serbia','628',' adulto','tellus non magna. Nam ligula',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (27,'69','Samantha Beach','84','Panama','322',' adulto','sem. Pellentesque ut',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (28,'23','Robin Sherman','52','Holy See (Vatican City State)','966','todos ','ipsum.',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (29,'05','Cameron Collier','13','Liechtenstein','537',' joven ','ante lectus',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (30,'81','Yvette Pratt','67','Argentina','603','todos ','enim,',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (31,'50','Ethan Warner','04','Costa Rica','679','todos ','Curabitur massa. Vestibulum',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (32,'44','Catherine Travis','60','Malaysia','934',' adulto','laoreet lectus quis massa. Mauris',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (33,'85','Hillary Wilcox','63','Myanmar','713',' adulto','sagittis placerat. Cras dictum ultricies',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (34,'57','Marshall Randall','93','Benin','808','todos ','egestas blandit. Nam nulla',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (35,'84','Violet Massey','00','Niger','214',' joven ','Phasellus in felis. Nulla',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (36,'50','Graham Mcdowell','96','Saint Kitts and Nevis','346',' joven ','varius et, euismod et, commodo',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (37,'20','Lee Gordon','13','Saint Martin','307',' adulto','Mauris nulla.',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (38,'52','Yardley Mcdonald','90','Croatia','202',' adulto','iaculis',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (39,'30','Brennan Olson','60','Nepal','571',' adulto','Donec',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (40,'79','Louis Gomez','44','Croatia','249',' joven ','eleifend vitae,',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (41,'70','Caesar Dominguez','68','Panama','349','todos ','auctor',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (42,'81','Scarlett Fowler','11','Iran','835',' adulto','arcu. Nunc mauris. Morbi non',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (43,'08','Lillith Burke','74','Jersey','334','todos ','nisl elementum',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (44,'68','Chloe Henson','84','Burundi','327',' adulto','massa. Integer vitae nibh. Donec',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (45,'63','Hasad Henderson','09','Namibia','048',' adulto','ultrices posuere cubilia',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (46,'17','Lev Moran','14','Portugal','369','todos ','odio tristique',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (47,'80','Odette Goodman','76','Macao','849',' joven ','vestibulum. Mauris magna. Duis dignissim',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (48,'80','Cameron Andrews','91','Kyrgyzstan','716','todos ','Phasellus',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (49,'90','Ifeoma Douglas','84','Svalbard and Jan Mayen Islands','354',' joven ','eget metus',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (50,'87','Cain Parrish','08','Somalia','046','todos ','per inceptos hymenaeos.',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (51,'61','Odysseus Patterson','39','Virgin Islands, British','775',' joven ','et malesuada fames ac',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (52,'05','George Collier','54','Indonesia','617',' joven ','sit amet, risus. Donec nibh',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (53,'03','Gwendolyn Simpson','41','United Kingdom (Great Britain)','116','todos ','Nulla semper tellus id',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (54,'83','Sawyer Salazar','43','Virgin Islands, British','342',' adulto','lacinia at, iaculis',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (55,'10','Micah Hutchinson','62','United States Minor Outlying Islands','266',' adulto','diam dictum',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (56,'79','Inga Santos','51','Guam','958','todos ','augue, eu tempor erat neque',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (57,'88','Virginia Mitchell','98','Kenya','562',' adulto','mi, ac mattis velit',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (58,'54','Jin Castillo','26','Congo, the Democratic Republic of the','499',' adulto','egestas hendrerit neque. In',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (59,'77','Denise Lewis','07','Afghanistan','635',' adulto','urna. Nunc',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (60,'60','Eaton Hurst','40','Philippines','410',' joven ','lorem vitae odio sagittis semper.',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (61,'41','Meredith Mcguire','59','Cocos (Keeling) Islands','961',' adulto','magna. Phasellus',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (62,'48','Dawn Merrill','82','Slovenia','792',' joven ','et',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (63,'44','Uriah Benton','25','United States','678',' adulto','vulputate mauris sagittis placerat. Cras',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (64,'87','Ethan Petersen','99','Zambia','780','todos ','lacus',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (65,'12','Martha Roach','26','United Kingdom (Great Britain)','736',' adulto','Proin vel nisl. Quisque fringilla',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (66,'87','Hyatt Reid','38','Denmark','791',' adulto','consectetuer rhoncus. Nullam velit dui,',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (67,'23','Erica Mercado','26','Uruguay','661',' joven ','Sed molestie. Sed id',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (68,'99','Hiram Hammond','21','Gabon','063','todos ','ac turpis egestas. Aliquam',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (69,'46','Hashim Fischer','55','Greece','605','todos ','fringilla est. Mauris',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (70,'18','Merrill Morales','24','Papua New Guinea','032',' adulto','semper tellus',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (71,'01','Hunter Sanchez','72','Malawi','314','todos ','rutrum. Fusce dolor quam, elementum',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (72,'54','Adena Reyes','16','Madagascar','272',' joven ','Nulla tincidunt, neque vitae',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (73,'15','Xerxes Perry','13','Bahrain','782',' joven ','metus urna convallis erat,',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (74,'39','Stewart Stanton','40','Brazil','293',' adulto','a',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (75,'44','Yael Gamble','57','Spain','810','todos ','auctor',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (76,'53','Orlando Dillon','96','Belgium','414',' joven ','consequat nec, mollis vitae,',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (77,'05','Mara Roy','64','Austria','071',' joven ','imperdiet, erat nonummy',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (78,'67','Kameko Rosa','42','Kuwait','700',' adulto','nisl.',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (79,'38','Nigel Abbott','40','Ireland','942',' joven ','diam. Duis mi enim,',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (80,'10','Griffith Molina','57','Georgia','600',' adulto','erat. Vivamus',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (81,'94','Richard Galloway','78','Iran','030','todos ','Suspendisse ac metus vitae velit',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (82,'39','Xaviera Fitzpatrick','21','Egypt','710',' joven ','in consectetuer ipsum',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (83,'91','Holly Walker','94','Grenada','476',' adulto','interdum',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (84,'86','Dana Pollard','66','Puerto Rico','446','todos ','nec',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (85,'15','Felix Walsh','80','Saint Martin','937',' joven ','et tristique pellentesque, tellus sem',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (86,'91','MacKensie Witt','13','Egypt','274',' joven ','dictum mi,',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (87,'26','Alfonso Bartlett','80','Macao','714','todos ','nibh vulputate mauris sagittis',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (88,'14','Kai Sellers','43','Andorra','835',' adulto','et magnis dis parturient montes,',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (89,'34','Byron Pearson','49','Tuvalu','635',' adulto','Cras',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (90,'86','Gray Parsons','93','Falkland Islands','700','todos ','Quisque purus sapien, gravida',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (91,'64','Zachery Elliott','40','Benin','916','todos ','auctor non,',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (92,'69','Anjolie Mcdowell','24','Gibraltar','100',' adulto','velit in aliquet lobortis, nisi',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (93,'48','Kim Leblanc','64','Luxembourg','381',' joven ','metus. In nec orci. Donec',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (94,'47','Martina Fischer','26','Brunei','227',' adulto','Cras pellentesque. Sed dictum. Proin',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (95,'58','Maggy Charles','10','Maldives','223','todos ','elit, a feugiat',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (96,'54','Paki Bradshaw','04','Belize','622',' joven ','Ut tincidunt vehicula',1);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (97,'54','Julie Barber','67','Papua New Guinea','154',' adulto','vestibulum',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (98,'04','Luke Waller','84','Palestine, State of','300',' adulto','nec urna et arcu',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (99,'78','Jelani Gates','30','Bonaire, Sint Eustatius and Saba','161','todos ','Class aptent taciti sociosqu',0);
INSERT INTO ESPECTACULO (ID,ID_COMPANIA,NOMBRE,DURACION,LENGUAJE,COSTO_PRODUCCION,PUBLICO,DESCRIPCION,TRADUCCION) VALUES (100,'01','McKenzie Fields','25','Germany','766',' adulto','Pellentesque ut ipsum ac',0);

COMMIT;