CREATE TABLE PRESENTA
(
	ID_FUNCION NUMBER NOT NULL,
	ID_SITIO NUMBER NOT NULL,
	CONSTRAINT PK_PRESENTA PRIMARY KEY(ID_FUNCION, ID_SITIO),
	CONSTRAINT FK_FUNCIONP
		FOREIGN KEY(ID_FUNCION) REFERENCES FUNCION(ID),
	CONSTRAINT FK_SITIOP
		FOREIGN KEY(ID_SITIO) REFERENCES SITIO(ID)
);

INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('12','18');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('74','67');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('36','35');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('37','93');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('35','26');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('67','16');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('81','66');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('51','19');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('79','47');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('50','09');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('53','25');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('48','71');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('73','81');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('17','24');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('72','90');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('55','99');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('10','98');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('53','70');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('06','27');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('48','78');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('30','95');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('81','92');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('69','24');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('45','81');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('60','03');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('69','37');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('29','68');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('70','04');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('82','07');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('52','64');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('19','32');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('76','81');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('14','56');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('96','16');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('14','01');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('66','80');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('00','82');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('72','39');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('05','83');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('67','20');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('19','37');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('76','07');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('29','50');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('53','07');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('03','25');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('49','47');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('38','31');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('31','12');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('29','22');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('07','28');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('76','37');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('92','96');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('62','19');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('70','61');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('45','00');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('66','47');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('28','92');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('45','61');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('80','43');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('91','65');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('96','98');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('08','27');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('43','62');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('09','60');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('92','09');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('94','54');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('12','31');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('54','36');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('90','78');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('02','09');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('32','64');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('44','32');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('58','07');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('37','43');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('95','26');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('42','27');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('09','49');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('20','84');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('20','19');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('47','35');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('99','57');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('72','77');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('81','53');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('38','96');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('08','96');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('09','26');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('91','02');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('19','58');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('29','28');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('46','53');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('03','46');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('38','74');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('98','29');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('66','66');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('02','12');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('38','22');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('17','85');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('74','71');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('89','20');
INSERT INTO PRESENTA (ID_FUNCION,ID_SITIO) VALUES ('55','22');

COMMIT;