CREATE TABLE SILLA
(
	ID NUMBER NOT NULL,
	ID_LOCALIDAD NUMBER NOT NULL,
	FILA VARCHAR(255),
	NUMERO NUMBER NOT NULL,
	
	CONSTRAINT PK_SILLA PRIMARY KEY(ID),
	CONSTRAINT FK_LOCALIDAD FOREIGN KEY(ID_LOCALIDAD) REFERENCE LOCALIDAD(ID),
);

INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (1,'63','R','90');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (2,'33','F','50');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (3,'04','H','57');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (4,'84','H','63');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (5,'28','J','56');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (6,'39','L','75');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (7,'91','K','31');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (8,'35','X','49');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (9,'70','Q','88');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (10,'95','L','81');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (11,'13','U','83');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (12,'82','O','81');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (13,'88','P','18');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (14,'69','X','01');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (15,'17','S','65');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (16,'75','I','89');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (17,'46','Y','03');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (18,'32','J','95');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (19,'13','M','55');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (20,'65','B','13');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (21,'79','X','70');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (22,'52','B','80');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (23,'07','X','91');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (24,'24','W','58');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (25,'61','G','99');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (26,'37','D','57');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (27,'83','H','49');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (28,'93','U','69');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (29,'23','C','63');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (30,'16','V','92');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (31,'36','G','66');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (32,'31','T','32');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (33,'18','Z','96');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (34,'49','L','92');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (35,'69','L','21');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (36,'55','O','25');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (37,'13','Q','44');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (38,'60','T','22');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (39,'36','M','84');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (40,'31','N','44');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (41,'90','F','64');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (42,'29','Z','35');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (43,'03','N','79');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (44,'02','K','11');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (45,'12','C','05');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (46,'92','Q','71');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (47,'36','N','09');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (48,'74','J','16');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (49,'62','Y','82');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (50,'11','V','98');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (51,'29','Y','25');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (52,'36','U','12');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (53,'40','U','96');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (54,'12','H','47');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (55,'65','Y','54');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (56,'76','N','36');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (57,'91','H','14');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (58,'81','M','27');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (59,'98','O','46');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (60,'77','B','44');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (61,'86','P','11');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (62,'42','V','45');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (63,'65','X','26');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (64,'53','L','75');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (65,'50','J','99');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (66,'50','G','72');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (67,'45','O','85');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (68,'21','Z','97');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (69,'60','R','27');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (70,'16','I','79');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (71,'21','Z','87');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (72,'14','S','55');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (73,'53','C','41');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (74,'31','S','61');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (75,'72','U','66');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (76,'02','F','93');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (77,'14','L','80');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (78,'88','M','10');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (79,'27','B','95');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (80,'33','U','46');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (81,'76','O','92');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (82,'57','C','14');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (83,'34','B','88');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (84,'38','Y','41');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (85,'72','G','87');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (86,'78','Q','48');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (87,'16','Z','59');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (88,'71','T','79');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (89,'43','E','37');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (90,'84','I','27');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (91,'82','M','02');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (92,'63','N','16');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (93,'61','I','17');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (94,'66','B','54');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (95,'60','N','73');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (96,'81','P','99');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (97,'28','F','74');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (98,'81','P','63');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (99,'02','E','47');
INSERT INTO SILLA (ID,ID_LOCALIDAD,FILA,NUMERO) VALUES (100,'33','L','86');

COMMIT;