CREATE TABLE SITIO
(
	ID NUMBER NOT NULL,
	NOMBRE VARCHAR(255),
	ABIERTO NUMBER NOT NULL,
	TIPO VARCHAR(255),
	APTO NUMBER NOT NULL,
	SILLETERIA VARCHAR(255),
	PROTECCION NUMBER NOT NULL,
	
	CONSTRAINT PK_SITIO PRIMARY KEY(ID)
);

INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (0,'Glenna Benson',1,'Lydia',1,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (1,'Eve Long',0,'Darius',0,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (2,'Ivan Nicholson',0,'Merritt',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (3,'Hamish Oconnor',1,'Larissa',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (4,'Henry Molina',0,'Maia',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (5,'Chava Kirk',0,'Raven',1,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (6,'Zorita Clayton',1,'Robin',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (7,'Blaze Roberson',1,'Marah',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (8,'Kiara Travis',1,'Sharon',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (9,'Fletcher Bright',1,'Andrew',0,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (10,'Rashad Nelson',1,'Nora',0,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (11,'James Poole',1,'Kaseem',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (12,'Blake Rocha',1,'Colin',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (13,'Calvin Kidd',0,'Orli',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (14,'Alea Snider',0,'Idona',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (15,'Patrick Harris',0,'Alan',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (16,'Britanney Klein',0,'Aurelia',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (17,'George Barber',0,'Beatrice',1,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (18,'Hiram Brock',0,'Leah',1,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (19,'Idona Clemons',1,'Liberty',0,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (20,'Ava Caldwell',0,'Phyllis',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (21,'Ian Bridges',0,'India',0,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (22,'Fuller Marks',1,'Desiree',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (23,'Oleg Horton',1,'Kaitlin',1,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (24,'Nichole Harris',1,'Larissa',0,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (25,'Ethan Glover',1,'Rebekah',1,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (26,'Brianna Gutierrez',0,'Brody',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (27,'Kermit Owen',1,'Ella',0,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (28,'Lester Payne',0,'Sierra',0,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (29,'Randall Valentine',1,'Callie',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (30,'Emmanuel Cox',1,'Jeanette',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (31,'Barclay Stanton',1,'Malik',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (32,'Janna Huber',0,'Yetta',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (33,'Dale Mcbride',0,'Leslie',1,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (34,'Astra Cunningham',1,'Fulton',1,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (35,'Octavia Tillman',0,'Jeremy',1,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (36,'Dustin Hickman',0,'Byron',0,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (37,'Raymond Sloan',0,'Adria',1,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (38,'Alea Valdez',1,'Darius',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (39,'Amery Fischer',1,'Amelia',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (40,'Demetrius Nichols',0,'Aubrey',1,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (41,'Cairo Yates',1,'Emerald',0,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (42,'Igor Massey',1,'Jael',0,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (43,'Darrel Dunlap',1,'Imani',1,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (44,'Hiram George',0,'Mason',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (45,'Larissa Santana',1,'Sydney',0,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (46,'Wing Burton',0,'Damian',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (47,'Holly May',0,'Jana',0,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (48,'Brynn Richard',0,'Serena',0,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (49,'Thomas Woodward',1,'Cameran',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (50,'Kasimir Hodge',1,'Joel',1,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (51,'Abigail Mccullough',0,'Quon',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (52,'Shad Merritt',1,'Forrest',1,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (53,'Illiana Chase',1,'Anthony',1,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (54,'Desirae Perez',1,'Cailin',0,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (55,'Beatrice Gilmore',1,'Carl',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (56,'Alan Park',0,'Andrew',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (57,'Lane Frazier',0,'Holly',1,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (58,'Burke Duffy',0,'Gisela',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (59,'Xandra Lynch',1,'Indira',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (60,'Mia Mathis',1,'Blaine',0,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (61,'Gemma Oneill',0,'Brett',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (62,'Maggie Roberts',1,'Isaiah',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (63,'Jescie Pollard',0,'Uma',1,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (64,'Oleg Clark',0,'Teagan',0,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (65,'Sylvia Myers',1,'Maite',0,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (66,'Samantha Bernard',1,'Serina',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (67,'Walter Vang',0,'Chadwick',0,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (68,'Daria Vazquez',0,'Boris',0,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (69,'Karyn Romero',1,'Venus',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (70,'Brooke Lancaster',1,'Tara',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (71,'Ila Hoover',0,'Gretchen',0,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (72,'Perry Hammond',1,'Reese',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (73,'May Olsen',0,'Oliver',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (74,'Perry Conley',1,'Cadman',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (75,'Yvette Workman',1,'Nita',0,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (76,'Eve Fry',0,'Jaime',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (77,'Xenos Hammond',0,'Hamilton',0,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (78,'Ashton Whitehead',0,'Derek',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (79,'Igor Bates',1,'Deacon',0,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (80,'Shelly Carter',1,'Chandler',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (81,'Cheyenne Sawyer',1,'Clarke',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (82,'Chaim Wood',0,'Vaughan',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (83,'Matthew Cortez',0,'Drake',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (84,'Clark Byers',1,'Alexa',1,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (85,'Justine Lamb',1,'Rachel',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (86,'Keiko Mclean',1,'Edward',1,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (87,'Miranda Montoya',1,'Lesley',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (88,'Lars Holder',1,'Alexandra',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (89,'Xaviera White',1,'Nerea',0,2,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (90,'Keane Barry',0,'Chase',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (91,'Cynthia Shields',1,'Shay',1,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (92,'MacKenzie Chambers',1,'Quinn',0,2,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (93,'Ivy Hammond',1,'Iliana',1,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (94,'Jane Daniels',1,'Conan',0,1,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (95,'Damian Mccormick',1,'Stacy',0,0,0);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (96,'Sylvester Austin',1,'Chase',0,0,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (97,'Grady Herring',1,'Latifah',1,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (98,'Cally Kinney',0,'Linus',0,1,1);
INSERT INTO SITIO (ID,NOMBRE,ABIERTO,TIPO,APTO,SILLETERIA,PROTECCION) VALUES (99,'Keefe Mcfadden',0,'Anjolie',0,1,1);

COMMIT;